var pokemonList = [
    {name: "Bulbasaur", type: 'plant', flying: false}, 
    {name: "Ivysaur", type: 'plant', flying: false}, 
    {name: "Venusaur", type: 'plant', flying: false}, 
    {name: "Charmander", type: 'fire', flying: false}, 
    {name: "Charmeleon", type: 'fire', flying: false}, 
    {name: "Charizard", type: 'fire', flying: false}, 
    {name: "Squirtle", type: 'water', flying: false}, 
    {name: "Wartortle", type: 'water', flying: false}, 
    {name: "Blastoise", type: 'water', flying: false}, 
    {name: "Caterpie", type: 'bug', flying: false}, 
    {name: "Metapod", type: 'bug', flying: false}, 
    {name: "Butterfree", type: 'bug', flying: false}, 
    {name: "Weedle", type: 'bug', flying: false}, 
    {name: "Kakuna", type: 'bug', flying: false}, 
    {name: "Beedrill", type: 'bug', flying: true}, 
    {name: "Pidgey", type: 'flying', flying: true}, 
    {name: "Pidgeotto", type: 'flying', flying: true}, 
    {name: "Pidgeot", type: 'flying', flying: true}, 
    {name: "Rattata", type: 'normal', flying: false}, 
    {name: "Raticate", type: 'normal', flying: false},
]
    /*
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidoran",
    "Nidorina",
    "Nidoqueen",
    "Nidoran",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch'd",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr.Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew"
*/
